export const therapists = [
  {
    id: "1",
    name: "Dr. Anjali Sharma",
    specialization: "Anxiety and Depression",
    contactNumber: "+91 98765 43210",
    email: "anjali.sharma@therapy.com",
    address: "123, Wellness Road, Bandra",
    city: "Mumbai",
    state: "Maharashtra",
  },
  {
    id: "2",
    name: "Dr. Vikram Singh",
    specialization: "Stress and Trauma",
    contactNumber: "+91 99887 76655",
    email: "vikram.singh@therapy.com",
    address: "456, Serenity Street, Koramangala",
    city: "Bengaluru",
    state: "Karnataka",
  },
  {
    id: "3",
    name: "Dr. Priya Desai",
    specialization: "Relationship Counseling",
    contactNumber: "+91 88776 65544",
    email: "priya.desai@therapy.com",
    address: "789, Harmony Lane, Hauz Khas",
    city: "New Delhi",
    state: "Delhi",
  },
    {
    id: "4",
    name: "Dr. Rohan Joshi",
    specialization: "Child and Adolescent Psychology",
    contactNumber: "+91 77665 54433",
    email: "rohan.joshi@therapy.com",
    address: "101, Joyful Avenue, Camp",
    city: "Pune",
    state: "Maharashtra",
  },
];
